FROM node:18-alpine

RUN apk add --no-cache curl jq

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY src ./src

ENV NODE_ENV=production
EXPOSE 3002

CMD ["node", "src/index.js"]